### ISSUE TITLE
Support for bump version before changelog is generated

### ISSUE THREAD

**Issue by Avcajaraville** [webpro/release-it#145]
Im having hard times trying to use this tool in our projects.

Im aware of an already existing issue here: https://github.com/webpro/release-it/issues/45

But the response there didn't helped me at all.

So, this is my node/npm configuration:
````
node v8.9.1
npm v5.5.1
OS Sierra 10.12.6
````

My setup for my projects is (only relevant chunks of code):
package.json
````
"scripts": {
  "release:patch": "release-it patch -c release.json"
}
````
And in my release.json (full file):
````
{
  "src": {
    "tagName": "v%s",
    "tagAnnotation": "Release v%s",
    "commitMessage": "Release v%s"
  },
  "github": {
    "release": true,
    "releaseName": "Release v%s",
    "tokenRef": "GITHUB_TOKEN"
  },
  "prompt": {
    "src": {
      "status": true,
      "commit": true,
      "tag": true,
      "push": true,
      "release": false,
      "publish": false
    }
  }
}
````

So, as stated on the previous linked question, theoretically if I just add (last key/value):
````
"src": {
    "tagName": "v%s",
    "tagAnnotation": "Release v%s",
    "commitMessage": "Release v%s",
    "beforeStageCommand": "my changelog script"
}
````
"my changelog command" will execute, but it doesn't.

I just need a reliable way of making conventional-changelog to run **after** version is bumped, so I can generate my changelog and have it committed in my release branch.

After the whole day digging, no success, and its a pity because I really want to use this package and not have to write my own script manually.

Thanks for your work, any help will be really appreciated.

**Comment by webpro** [comment]
Hi @Avcajaraville.

Sorry to hear you've wasted time. Looks like the solution is to use the `buildCommand`, which is executed right after the version is bumped. E.g.:

```
{
  "buildCommand": "my changelog script",
  "src": {},
  "github": {}
}
```

The `src. beforeStageCommand ` was removed as it was basically a duplicate of `buildCommand`. This was mentioned in the [release notes for v3](https://github.com/webpro/release-it/releases/tag/3.0.0). The ticket you mentioned is a bit old.

**Comment by Avcajaraville** [comment]
@webpro 

Alright, I also figured out your suggestion, but though it might be a little hackish.

Now my other issue is how can I write the release body on github using conventional-changelog.

Because till now, I have to stay with the git log and I want to have changelog and releases unified.

Is this possible ? Remember, changelog should execute AFTER the version is bumped, otherwise, it wont work.

BTW; I will be keen to make a PR reflecting the buildCommand option, if you want, please indicate from where should I branch (master) and if there is anything else to document :)

Thanks for your quick reply and good job :)

**Comment by webpro** [comment]
> Now my other issue is how can I write the release body on github using conventional-changelog.

There is no built-in support for this. The changelog command runs before the version bump. This is because release-it, in interactive mode, asks for confirmation (while showing the changelog) before making any changes.

Is there a way to feed/override the bumped version to `conventional-changelog`? E.g. a command such as `conventional-changelog --previousTag={latestVersion} --currentTag={version}`. We would only need to do the replacements like in the `buildCommand` (which has _just_ been [discussed](https://github.com/webpro/release-it/issues/150#issuecomment-343957111)).

> BTW; I will be keen to make a PR reflecting the buildCommand option

Not sure I understand, could you please clarify this?

**Comment by Avcajaraville** [comment]
@webpro 

> Not sure I understand, could you please clarify this?

Yes, I meant that the buildCommand option wasn't clear for me on the documentation.

But now, looking at it twice, seems that I just missed it. Maybe we can add when the version have changed; for instance:

The command hooks are executed from the root directory of the src or dist repository, respectively:
- src.beforeStartCommand (version not bumped)
- buildCommand - before files are staged for commit  (version bumped)
... etc

Just a suggestion to make this more clear.

About the release-it in interactive mode, I was thinking about an option such as: ````options.bumpBeforeChangelog````; this could be a boolean that actually bumps the version before executing the changelog command. This will solve both problems I had and potentially also the issue you mentioned on your previous comment.

This can be undo by keeping a reference of the previous version in case the confirmation step is canceled on the cli.

Would this be something worth to work on ?

**Comment by webpro** [comment]
Thanks for clearing that up. I agree the docs could be improved on.

The "bump before changelog" would not align well with the current flow. Here is a different approach that might work, although it might feel a bit hack-ish:

```
"changelogCommand": "cat changelog.txt",
"src": {
  "beforeStartCommand": "conventional-changelog-command > changelog.txt",
}
```

The `src.beforeStartCommand` is executed first, and the output of `changelogCommand` will be used for the changelog. Note that `${version}` (and `${latestVersion}`) are not available yet in the `src.beforeStartCommand`. Would that work for you?

**Comment by Avcajaraville** [comment]
@webpro 

The solution you suggested on your previous comment didn't worked out for me, reasons being, as you pointed out, `changelogCommand` being executed before version is bumped.

I honestly believe the `options.bumpBeforeChangelog` is a very nice solution, and being this properly documented and as default value to false, I don't see why it won't fit the current workflow.

At the is just an option you use or not. I would be happy to maybe try to implement it, or to see this happening, because at the end I ended up with a much more hack-ish solution.

I do believe that a lot of people comes to your repo and try to use conventional-changelog, as this is really popular. The only issue being the releases on github wont use it. And thats a shame :)

As reference for people coming to this issue, I will now post my solution:

pacakge.json:
```
"scripts": {
    "changelog": "conventional-changelog -p angular -i CHANGELOG.md -s",
    "release:patch": "npm version patch --no-git-tag-version && release-it patch -c release.json",
    "release:minor": "npm version minor --no-git-tag-version && release-it minor -c release.json",
    "release:major": "npm version major --no-git-tag-version && release-it major -c release.json"
}
```
The trick here is to update the version with npm and not generate tags or commits.

Then on the options passed to release-it (release.json):
```
{
  "changelogCommand": "conventional-changelog -p angular && git checkout .",
  "buildCommand": "npm run changelog",
  "src": {
    "tagName": "v%s",
    "tagAnnotation": "Release v%s",
    "commitMessage": "Release v%s"
  },
  "github": {
    "release": true,
    "releaseName": "Release v%s",
    "tokenRef": "GITHUB_TOKEN"
  },
  "prompt": {
    "src": {
      "status": true,
      "commit": true,
      "tag": true,
      "push": true,
      "release": false,
      "publish": false
    }
  }
}
```
The key here was to run `conventional-changelog` on `changelogCommand` and because we already bumped the version with npm, undo those changes via `git checkout .`.

PS: Im aware that any changes on my working directory will be lost with this command, but thats fine since we are creating releases and working directory should be clean at this point.

**Comment by webpro** [comment]
> The solution you suggested on your previous comment didn't worked out for me, reasons being, as you pointed out, `changelogCommand` being executed before version is bumped.

Ah yes, sorry, that should be `buildCommand` instead of `src.beforeStartCommand`. But that would not work because `changelogCommand` runs before `buildCommand`.

> I honestly believe the `options.bumpBeforeChangelog` is a very nice solution, and being this properly documented and as default value to false, I don't see why it won't fit the current workflow.

What I meant was the flow in the code.

However, feel free to start a PR, I'm happy to support a workflow using conventional-changelog.

**Comment by Avcajaraville** [comment]
@webpro Alright then, without promising, as Im loaded with work now at days, I will try to eventually create a PR for this request. 

Feel free to close this ticket or I will once I got a PR :)

I do believe we can do this feature, and even more that this module is being added as dependency to our projects (we wont forget this way).

Thanks for your helpful and quick responses. You are doing a great job with this module and the supported provided :)

**Comment by webpro** [comment]
I have just released something that might work with this scenario ([v5.2.0-alpha.0](https://github.com/webpro/release-it/releases/tag/5.2.0-alpha.0)). It's a bit generic (not specific to conventional-changelog), but was obviously inspired a lot by this use case.

Install this with `npm install release-it@alpha`

The related config to override:

```
{
  "increment": "conventional:changelog", // get recommended bump by conventional-recommended-bump
  "safeBump": false, // bumps eagerly, before `beforeChangelogCommand`
  "beforeChangelogCommand": "conventional-changelog -p angular -i CHANGELOG.md -s",
  "changelogCommand": "conventional-changelog -p angular -i CHANGELOG.md",
}
```

Not sure what `changelogCommand` should contain. Ideally `conventional-changelog` can be run again, with output to stdout. It should output whatever changelog should go into the GitHub release.

What do you think, @Avcajaraville?

**Comment by Avcajaraville** [comment]
@webpro thanks for this :)

Unfortunately, this doesn't fit in my current setup neither, mostly due to wrong tag version, as now my settings for vX.X.X are ignore and just generate a tag like X.X.X

Also, not quite sure why do we need recommended bump, as far as I see that, that should be left to the developer (to decide which type of bump apply).

Just to recap, with your latests answer I change my config into:
- "increment": "conventional:angular" -> removed this option, as it have no effect for me, we use scripts like bump:patch, bump:minor & bump:major, it is up to the developer to choose one
- "safeBump": false -> ok, as specified
-  "beforeChangelogCommand": "npx conventional-changelog -p angular": this should returns the new additions since last release, the command does that
-  "changelogCommand": "npx conventional-changelog -p angular -i CHANGELOG.md": this should generate the whole changelog.md file, and the command does that though

My issues are:
- Wrong tag: as explained before, say my last tag is v1.0.1 and I do a release-it patch, new tag is 1.0.2 and not v1.0.2 as it should.
- Changelog.md file is not generated nor committed nor pushed.
- Release in github contains all commits (I believe this is because of the wrong tags) and its neither on the expected format (seems its use the default template).

Really looking forward to help and contribute with feedback :)

Maybe we can create a test repo where we can debug the behaviour.

**Comment by webpro** [comment]
Thanks for your elaborate reply.

* If the tag does not include the `v` (while you specified `tagName: "v%s"`), that's a bug. I'll look into that.
* Based on the [Angular conventional changelog](https://github.com/angular/angular.js/blob/master/DEVELOPERS.md#commits) commit rules, release-it can now automatically guess the appropriate bump. E.g. if there are `"feat(..): .."` commits, then it will do a minor bump. Of course this is just optional.
* Looks like you should swap the `beforeChangelogCommand` and `changelogCommand` commands.

**Comment by webpro** [comment]
@Avcajaraville I've looked into the tag name, and things are looking good to me. The tag is set properly and that also results in a GitHub release including the `v` in e.g. `v2.0.0`.

**Comment by Avcajaraville** [comment]
@webpro This still doesnt work for my current setup, and at this point, Im not sure what Im doing wrong.

This is my whole current setup:
- release-it version: 5.2.0-alpha.0
 
Scripts on package.json:
- "release:patch": "npx release-it patch"
- "release:minor": "npx release-it minor"
- "release:major": "npx release-it major"

.release-it.json:
```
{
  "safe-bump": false,
  "changelogCommand": "npx conventional-changelog -p angular",
  "buildCommand": "npx conventional-changelog -p angular -i CHANGELOG.md -s",
  "src": {
    "tagName": "v%s",
    "tagAnnotation": "Release v%s",
    "commitMessage": "Release v%s"
  },
  "github": {
    "release": true,
    "releaseName": "Release v%s",
    "tokenRef": "GITHUB_TOKEN"
  },
  "prompt": {
    "src": {
      "status": true,
      "commit": true,
      "tag": true,
      "push": true,
      "release": false,
      "publish": false
    }
  }
}
```

What happen now when I run `npm run release:patch` is that everything works as expected (tag numbers, version, CHANGELOG.md **but** release on github is wrong.

Consider the correct output for CHANGELOG.md
<img width="401" alt="captura de pantalla 2017-12-20 15 33 43" src="https://user-images.githubusercontent.com/2271201/34212035-3f673abe-e59b-11e7-9bde-05325b59cd81.png">
All good, newest commits prepended to the file.

But release on github is wrong:
<img width="485" alt="captura de pantalla 2017-12-20 15 33 23" src="https://user-images.githubusercontent.com/2271201/34212049-4f5f4344-e59b-11e7-90d8-a3aa0850361a.png">
Body of the release is just Release v1.0.2 instead of showing the actual changes.

That is something I really cant get.

Lets consider a manual update:

So I have my commits, then I update version manually and run: `npx conventional-changelog -p angular`. This command will print in stout the new commits, as demonstrated:
<img width="768" alt="captura de pantalla 2017-12-20 15 36 55" src="https://user-images.githubusercontent.com/2271201/34212188-cf8278d4-e59b-11e7-97b3-c2cc978ed0c4.png">

So the command works, but I suspect release-it (even with `safe-bump = false`) is not bumping version before the `changelogCommand`.

What am I missing ?

**Comment by webpro** [comment]
* It also took me a while, as I was surprised to get an empty changelog from conventional-changelog. But looking at `conventional-changelog --help`, it seems that the `-u` option provides the changelog for unreleased (untagged?) git history. This did the trick for me. Also remember to remove the first lines from the output for a GitHub release (see example below).
* I've released 5.2.0-rc.0 before which contains a bugfix (but seems unrelated to your situation)
* You can pass `--verbose` to release-it, so you can check the generated changelog before the question "Ready to release v#.#.#?" comes up.

```
"changelogCommand": "npx conventional-changelog -p angular -u | tail -n +3"
```

**Comment by Avcajaraville** [comment]
@webpro Sorry for my late answer, holidays happened and I gotta to disconnect.

After coming back, I did restart the set up in my project and did the following:
- update dependencies, now using ^5.2.0
- change the options to:
```
  "beforeChangelogCommand": "npm run changelog",
  "changelogCommand": "npx conventional-changelog -p angular | tail -n +3",
  "safeBump": false,
```

And voila ! Works as a charm !

Thanks a lot for your time and dedication, we really appreciate your work in my team :)

**Comment by webpro** [comment]
Cool! Thanks for your feedback.
